[versions]
    kotlin = "2.2.20"
    build-config = "5.6.5"
    bcv = "0.16.3"
    junit = "4.13.2"
    nexus-publish = "2.0.0"
    gradle-plugin-publish = "2.0.0"

[libraries]
    junit = { module = "junit:junit", version.ref = "junit" }
    nexus-publish = { module = "io.github.gradle-nexus.publish-plugin:io.github.gradle-nexus.publish-plugin.gradle.plugin", version.ref = "nexus-publish" }
    build-config = { module = "com.github.gmazzo.buildconfig:com.github.gmazzo.buildconfig.gradle.plugin", version.ref = "build-config" }

[plugins]
    kotlin-jvm = { id = "org.jetbrains.kotlin.jvm" }
    kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform" }
    build-config = { id = "com.github.gmazzo.buildconfig" }
    binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "bcv" }
    gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
